# Generated by Django 5.0.7 on 2024-08-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_routineexercise_routine_exercises_routinesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
